package com.example.envagemobileapplication.Models.RequestModels


data class AddJobRequestPayLoad(
    val jobDescription: String,
    val positionName: String,
    val clientId: Int,
    val payrollPayGroupId: Int,
    val jobId: Int,
    val industryId: Int,
    val jobNature: String,
    val address1: String,
    val address2: String,
    val country: String,
    val zipcode: String,
    val city: String,
    val state: String,
    val location: String,
    val headcount: Int,
    val jobType: String,
    val startDate: String,
    val endDate: String,
    val currency: String,
    val minimumSalary: Int,
    val maximumSalary: Int,
    val workingDaysNo: Int,
    val estimatedHours: Int,
    val workingDays: String,
    val jobStatusId: Int,
    val jobSkills: List<JobSkill>,
    //val experienceRequired : String
    //val useTemplate : false
    val markup: Int,
    val minPayRate: Double,
    val minBillRate: Double,
    val maxPayRate: Double,
    val maxBillRate: Double,
    val targetPayRate: Double,
    val targetBillRate: Double,
    val overTimeMultiplier: Double,
    val overTimeType: String,
    val overTimeMarkup: Int,
    val overTimePayRate: Double,
    val overTimeBillRate: Double,
    val doubleTimeMultiplier: Double,
    val doubleTimeType: String,
    val doubleTimeMarkup: Int,
    val doubleTimePayRate: Double,
    val doubleTimeBillRate: Double,
    val frequency: String,
    val applicationFormId: Int,
    val showSalary: Boolean,
    val showNature: Boolean,
    val showClient: Boolean,
    val showIndustry: Boolean,
    val showAddress: Boolean,
    val showType: Boolean,
    val showSkills: Boolean,
    val showShift: Boolean,
    val isPublish: Boolean
   // val jobPlatform : String
)

data class JobSkill(
    val skillId: Int,
    val name: String,
    val skillRating: String,
    val IsDeleted: Boolean,
    val jobId: Int
)