package com.example.envagemobileapplication.Models.RequestModels

class AssignJobRequestModel (
        val candidateJobId: Int,
        val companyId: Int,
        val candidateId: Int,
        val jobId: Int,
        val positionName: String,
        val jobStatusId: Int,
        val jobStatus: String,
        val colorCode: String,
        val clientId: Int,
        val clientProfilePicture: String,
        val clientName: String,
        val jobType: String,
        val country: String,
        val zipcode: String?,
        val city: String?,
        val state: String?,
        val location: String?,
        val jobNature: String,
        val statusId: String?,
        val status: String?,
        val statusColorCode: String?,
        val payRate: Double?,
        val billRate: Double?,
        val overtimePayRate: Double?,
        val overtimeBillRate: Double?,
        val doublePayRate: Double?,
        val doubleBillRate: Double?,
        val statusSequence: Int?,
        val isDeleted: Boolean,
        val offerSent: Boolean,
        val templateId: String?,
        val offerLetterLink: String?,
        val lastStatusId: String?,
        val lastStatus: String?,
        val lastStatusColorCode: String?,
        val joiningDate: String?,
        val offeredSalary: Double?,
        val jobGuid: String,
        val candidateGUID: String,
        val isNew: Boolean
    )


